config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "flats#index"

  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
    def index
        @flats = Flat.all
      end

      def show
        @flat = Flat.find(params[:id])
      end

      def new #render the form
        @flat = Flat.new
      end

      def create #save the form data
        #@article = Article.new(title: "...", body: "...")
        @flat = Flat.new(flat_params) #more secure than above with a hash

        if @flat.save
          redirect_to @flat
        else
          render :new, status: :unprocessable_entity
        end
      end

      def edit
        @flat = Flat.find(params[:id])
      end

      def update
        @flat = Flat.find(params[:id])

        if @flat.update(flat_params)
          redirect_to @flat
        else
          render :edit, status: :unprocessable_entity
        end
      end

      def destroy
        @flat = Flat.find(params[:id])
        @flat.destroy

        redirect_to root_path, status: :see_other
      end

      private
        def flat_params
          params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/flats/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-danger">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">AIRBNB</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"     aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#"><%= link_to "Home", flats_path, class:"home-link" %></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled">Disabled</a>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <button class="btn btn-dark" type="submit"><%= link_to "Add Flat", new_flat_path, class:"addflat-btn" %></button>
          </form>
        </div>
      </div>
   </nav>

app/views/flats/edit.html.erb
<%= render "navbar" %>

app/views/flats/index.html.erb
<%= render "navbar" %>
<h1>Welcome to the Flats (<%= @flats.count %>)</h1>

<div class="cards">
    <% @flats.each do |flat| %>
        <div class="card">
            <%= link_to flat.name, flat, class: "list" %>
            <%= link_to flat.address, flat, class: "address" %>
          <div>
            <span><%= link_to flat.price_per_night, flat, class: "price-per-night" %>$</span>
            <span><%= link_to flat.number_of_guests, flat, class: "n-guests" %></span>
          </div>
          <div class="more-info">
              <p>More Info</p>
          </div>
        </div>
    <% end %>
</div>



  <div id="image">
     Rooms
  </div>

app/views/flats/new.html.erb
<%= render "navbar" %>
<h1>New Flat</h1>

<%= form_with model: @flat do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <%= form.label :address %><br>
    <%= form.text_field :address %>
    <%= form.label :description %><br>
    <%= form.text_field :description %>
    <%= form.label :price_per_night %><br>
    <%= form.text_field :price_per_night %>
    <%= form.label :number_of_guests %><br>
    <%= form.text_field :number_of_guests %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/flats/show.html.erb
<%= render "navbar" %>
<h1><%= @flat.name %></h1>

<p><%= @flat.address %></p>

<ul>
  <%= link_to "Edit", edit_flat_path(@flat), class:"edit-btn" %>
  <%= link_to "Destroy", flat_path(@flat), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  }, class:"destroy-btn" %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>